name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs: 
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
       
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      
      - name: build docker image
        run: docker build . --file Dockerfile -t fauzanooor/stkbt_nginx
      
      - name: push docker image
        run: docker push fauzanooor/stkbt_nginx

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          headers: '{"repository": "joelwmale/webhook-action"}'
          body: '{"event": "deployment", "repository": "joelwmale/webhook-action"}'